// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: cart.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "cart.v1";

/** Currency enumeration for supported currencies */
export enum Currency {
  CURRENCY_UNSPECIFIED = 0,
  CURRENCY_USD = 1,
  CURRENCY_EUR = 2,
  CURRENCY_GBP = 3,
  CURRENCY_UAH = 4,
  UNRECOGNIZED = -1,
}

/** Message representing a user ID */
export interface UserId {
  userId: string;
}

/** Message representing a status response */
export interface StatusResponse {
  success: boolean;
  message: string;
}

/** Client-supplied fields only — price/currency are set server-side */
export interface CartItemInput {
  productId: string;
  variantId?: string | undefined;
  quantity: number;
}

/** Server-enriched cart item stored in Redis and returned in responses */
export interface CartItem {
  productId: string;
  variantId?: string | undefined;
  quantity: number;
  /** price snapshot at add time */
  price: number;
  currency: Currency;
}

/** Message representing a cart response */
export interface CartResponse {
  userId: string;
  items: CartItem[];
  total: number;
  currency: Currency;
}

/** Request to add an item to the cart */
export interface AddToCartRequest {
  userId: string;
  item: CartItemInput | undefined;
}

/** Request to update an item in the cart */
export interface UpdateCartItemRequest {
  userId: string;
  item: CartItemInput | undefined;
}

/** Request to remove an item from the cart */
export interface RemoveFromCartRequest {
  userId: string;
  productId: string;
  variantId?: string | undefined;
}

export const CART_V1_PACKAGE_NAME = "cart.v1";

/** CartService defines the gRPC service for managing shopping carts. */

export interface CartServiceClient {
  /** rpc to get a cart by user ID */

  getCart(request: UserId): Observable<CartResponse>;

  /** rpc to add an item to the cart */

  addToCart(request: AddToCartRequest): Observable<CartResponse>;

  /** rpc to update an item in the cart */

  updateCartItem(request: UpdateCartItemRequest): Observable<CartResponse>;

  /** rpc to remove an item from the cart */

  removeFromCart(request: RemoveFromCartRequest): Observable<CartResponse>;

  /** rpc to clear the cart */

  clearCart(request: UserId): Observable<StatusResponse>;
}

/** CartService defines the gRPC service for managing shopping carts. */

export interface CartServiceController {
  /** rpc to get a cart by user ID */

  getCart(request: UserId): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to add an item to the cart */

  addToCart(request: AddToCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to update an item in the cart */

  updateCartItem(request: UpdateCartItemRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to remove an item from the cart */

  removeFromCart(request: RemoveFromCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to clear the cart */

  clearCart(request: UserId): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function CartServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getCart", "addToCart", "updateCartItem", "removeFromCart", "clearCart"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CART_SERVICE_NAME = "CartService";
