// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: cart.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Currency } from "./store-item";

export const protobufPackage = "cart.v1";

/** Message representing a user ID */
export interface UserId {
  userId: string;
}

/** Message representing a status response */
export interface StatusResponse {
  success: boolean;
  message: string;
}

/** Client-supplied fields only — price/currency are set server-side */
export interface CartItemInput {
  productId: string;
  variantId?: string | undefined;
  quantity: number;
}

/** Server-enriched cart item stored in Redis and returned in responses */
export interface CartItem {
  productId: string;
  variantId?: string | undefined;
  quantity: number;
  /** price snapshot at add time */
  price: number;
  currency: Currency;
  title?: string | undefined;
  variantName?: string | undefined;
  imageUrl?: string | undefined;
}

/** Message representing a cart response */
export interface CartResponse {
  userId: string;
  items: CartItem[];
  total: number;
  currency: Currency;
  expiresAt?: string | undefined;
}

/** Request to add an item to the cart */
export interface AddToCartRequest {
  userId: string;
  item: CartItemInput | undefined;
}

/** Request to update an item in the cart */
export interface UpdateCartItemRequest {
  userId: string;
  item: CartItemInput | undefined;
}

/** Request to remove an item from the cart */
export interface RemoveFromCartRequest {
  userId: string;
  productId: string;
  variantId?: string | undefined;
}

export const CART_V1_PACKAGE_NAME = "cart.v1";

/** CartService defines the gRPC service for managing shopping carts. */

export interface CartServiceClient {
  /** rpc to get a cart by user ID */

  getCart(request: UserId): Observable<CartResponse>;

  /** rpc to add an item to the cart */

  addToCart(request: AddToCartRequest): Observable<CartResponse>;

  /** rpc to update an item in the cart */

  updateCartItem(request: UpdateCartItemRequest): Observable<CartResponse>;

  /** rpc to remove an item from the cart */

  removeFromCart(request: RemoveFromCartRequest): Observable<CartResponse>;

  /** rpc to clear the cart */

  clearCart(request: UserId): Observable<StatusResponse>;
}

/** CartService defines the gRPC service for managing shopping carts. */

export interface CartServiceController {
  /** rpc to get a cart by user ID */

  getCart(request: UserId): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to add an item to the cart */

  addToCart(request: AddToCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to update an item in the cart */

  updateCartItem(request: UpdateCartItemRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to remove an item from the cart */

  removeFromCart(request: RemoveFromCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to clear the cart */

  clearCart(request: UserId): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function CartServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getCart", "addToCart", "updateCartItem", "removeFromCart", "clearCart"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CART_SERVICE_NAME = "CartService";

/** WishlistService defines the gRPC service for managing user wishlists. */

export interface WishlistServiceClient {
  /** rpc to get a wishlist by user ID */

  getWishlist(request: UserId): Observable<CartResponse>;

  /** reusing CartResponse for wishlist since it has the same structure */

  addToWishlist(request: AddToCartRequest): Observable<CartResponse>;

  /** reusing RemoveFromCartRequest for wishlist since it has the same structure */

  removeFromWishlist(request: RemoveFromCartRequest): Observable<CartResponse>;

  /** rpc to move an item from wishlist to cart */

  moveToCart(request: RemoveFromCartRequest): Observable<CartResponse>;

  /** rpc to move an item from cart to wishlist */

  moveToWishlist(request: RemoveFromCartRequest): Observable<CartResponse>;
}

/** WishlistService defines the gRPC service for managing user wishlists. */

export interface WishlistServiceController {
  /** rpc to get a wishlist by user ID */

  getWishlist(request: UserId): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** reusing CartResponse for wishlist since it has the same structure */

  addToWishlist(request: AddToCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** reusing RemoveFromCartRequest for wishlist since it has the same structure */

  removeFromWishlist(request: RemoveFromCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to move an item from wishlist to cart */

  moveToCart(request: RemoveFromCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;

  /** rpc to move an item from cart to wishlist */

  moveToWishlist(request: RemoveFromCartRequest): Promise<CartResponse> | Observable<CartResponse> | CartResponse;
}

export function WishlistServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getWishlist",
      "addToWishlist",
      "removeFromWishlist",
      "moveToCart",
      "moveToWishlist",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WishlistService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WishlistService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WISHLIST_SERVICE_NAME = "WishlistService";
