// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               v6.33.2
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order.v1";

export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0,
  ORDER_STATUS_PENDING = 1,
  ORDER_STATUS_CONFIRMED = 2,
  ORDER_STATUS_PROCESSING = 3,
  ORDER_STATUS_SHIPPED = 4,
  ORDER_STATUS_DELIVERED = 5,
  ORDER_STATUS_CANCELLED = 6,
  ORDER_STATUS_REFUNDED = 7,
  UNRECOGNIZED = -1,
}

export enum Currency {
  CURRENCY_UNSPECIFIED = 0,
  CURRENCY_USD = 1,
  CURRENCY_EUR = 2,
  CURRENCY_GBP = 3,
  CURRENCY_UAH = 4,
  UNRECOGNIZED = -1,
}

export enum PriceType {
  PRICE_TYPE_UNSPECIFIED = 0,
  PRICE_TYPE_REGULAR = 1,
  PRICE_TYPE_DISCOUNT = 2,
  PRICE_TYPE_WHOLESALE = 3,
  UNRECOGNIZED = -1,
}

export interface OrderId {
  id: string;
}

export interface OrderItemInput {
  productId: string;
  variantId?: string | undefined;
  title: string;
  variantName?: string | undefined;
  imageUrl?: string | undefined;
  quantity: number;
  unitPrice: number;
  currency: Currency;
  priceType: PriceType;
}

export interface OrderItemResponse {
  id: string;
  productId: string;
  variantId?: string | undefined;
  title: string;
  variantName?: string | undefined;
  imageUrl?: string | undefined;
  quantity: number;
  unitPrice: number;
  currency: Currency;
  priceType: PriceType;
}

export interface OrderResponse {
  id: string;
  userId: string;
  status: OrderStatus;
  currency: Currency;
  totalPrice: number;
  notes?: string | undefined;
  items: OrderItemResponse[];
  createdAt: string;
  updatedAt: string;
}

export interface OrderListResponse {
  orders: OrderResponse[];
  total: number;
}

export interface CreateOrderRequest {
  userId: string;
  items: OrderItemInput[];
  notes?: string | undefined;
  idempotencyKey?: string | undefined;
}

export interface GetOrdersByUserRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface UpdateOrderStatusRequest {
  id: string;
  status: OrderStatus;
}

export interface CancelOrderRequest {
  id: string;
  userId: string;
}

export const ORDER_V1_PACKAGE_NAME = "order.v1";

/** OrderService defines the gRPC service for managing orders. */

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest): Observable<OrderResponse>;
  getOrder(request: OrderId): Observable<OrderResponse>;
  getOrdersByUser(request: GetOrdersByUserRequest): Observable<OrderListResponse>;
  updateOrderStatus(request: UpdateOrderStatusRequest): Observable<OrderResponse>;
  cancelOrder(request: CancelOrderRequest): Observable<OrderResponse>;
}

/** OrderService defines the gRPC service for managing orders. */

export interface OrderServiceController {
  createOrder(request: CreateOrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;
  getOrder(request: OrderId): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;
  getOrdersByUser(
    request: GetOrdersByUserRequest,
  ): Promise<OrderListResponse> | Observable<OrderListResponse> | OrderListResponse;
  updateOrderStatus(request: UpdateOrderStatusRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;
  cancelOrder(request: CancelOrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createOrder",
      "getOrder",
      "getOrdersByUser",
      "updateOrderStatus",
      "cancelOrder",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
