// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: user.proto

/* eslint-disable */
import { Observable } from "rxjs";

export const protobufPackage = "user.v1";

export enum UserRole {
  USER = 0,
  ADMIN = 1,
  MODERATOR = 2,
  VISITOR = 3,
  UNRECOGNIZED = -1,
}

export interface Id {
  id: string;
}

export interface User {
  id: string;
  name?: string | null;
  email: string;
  phoneNumber?: string | null;
  role: UserRole;
  avatarUrl?: string | null;
  passwordHash?: string | null;
  isEmailVerified: boolean;
  lastLogin?: Date | null;
  isBanned: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export const USER_V1_PACKAGE_NAME = "user.v1";

export const USER_SERVICE_NAME = "UserService";

export interface UserServiceClient {
  getUserById(request: Id): Observable<User>;
}
